// <auto-generated />
namespace QTech.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v10_IntializeDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v10_IntializeDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202205080940582_v1.0_IntializeDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
